/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.*;
import Negocio.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Grupo2
 */
public class PantallaMantenedorCliente extends javax.swing.JFrame {

    private int fila;
    private int ultimo;
    
    /**
     * Creates new form PantallaMantenedorCliente
     */
    public PantallaMantenedorCliente() {
        this.setFila(1);
        initComponents();
    }

    public void mostrar()
    {
       Negocio auxNegocio = new Negocio();
       this.setUltimo(auxNegocio.retornaCliente().size());
       
       Cliente auxCliente = new Cliente();
       
       auxCliente = auxNegocio.posicionaCliente(this.getFila());
       
       this.txtRut.setText(auxCliente.getRut());
       this.txtNombre.setText(auxCliente.getNombre());
       String auxPosicion = this.getFila() + "-" 
                            + this.getUltimo();
       this.txtPosicion.setText(auxPosicion); 
       
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtPosicion = new javax.swing.JTextField();
        btoGuardar = new javax.swing.JButton();
        btoEliminar = new javax.swing.JButton();
        btoActuralizar = new javax.swing.JButton();
        btoConsultar = new javax.swing.JButton();
        btoSalir = new javax.swing.JButton();
        btoPrimero = new javax.swing.JButton();
        btoAnterior = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btoSiguiente = new javax.swing.JButton();
        btoUltimo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Rut");

        jLabel2.setText("Nombre");

        btoGuardar.setText("Guardar");
        btoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoGuardarActionPerformed(evt);
            }
        });

        btoEliminar.setText("Eliminar");
        btoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoEliminarActionPerformed(evt);
            }
        });

        btoActuralizar.setText("Actualizar");

        btoConsultar.setText("Consultar");
        btoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoConsultarActionPerformed(evt);
            }
        });

        btoSalir.setText("Salir");
        btoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalirActionPerformed(evt);
            }
        });

        btoPrimero.setText("<|");
        btoPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoPrimeroActionPerformed(evt);
            }
        });

        btoAnterior.setText("<");
        btoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoAnteriorActionPerformed(evt);
            }
        });

        btoSiguiente.setText(">");
        btoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSiguienteActionPerformed(evt);
            }
        });

        btoUltimo.setText("|>");
        btoUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btoGuardar)
                            .addComponent(btoPrimero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btoEliminar)
                            .addComponent(btoAnterior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPosicion)
                            .addComponent(btoActuralizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btoConsultar)
                            .addComponent(btoSiguiente))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btoUltimo)
                            .addComponent(btoSalir))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoGuardar)
                    .addComponent(btoEliminar)
                    .addComponent(btoActuralizar)
                    .addComponent(btoConsultar)
                    .addComponent(btoSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btoPrimero)
                    .addComponent(btoAnterior)
                    .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btoSiguiente)
                    .addComponent(btoUltimo))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.gc();
    }//GEN-LAST:event_btoSalirActionPerformed

    private void btoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoConsultarActionPerformed
        // TODO add your handling code here:
        PantallaConsultaCliente pConsulta = new PantallaConsultaCliente();
        pConsulta.setVisible(true);
        
        
    }//GEN-LAST:event_btoConsultarActionPerformed

    public void limpiarCampos()
    {
       this.txtRut.setText("");
       this.txtNombre.setText("");
       this.txtRut.requestFocus();
    }
    
    
    private void btoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoGuardarActionPerformed
        // TODO add your handling code here:

        
        try
        {
            if (this.txtRut.getText().isEmpty() || 
                this.txtNombre.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Ingresa Datos Gil" );
            } //Fin if campos en blanco
            else
            {
               Cliente auxCliente = new Cliente();
               auxCliente.setRut(this.txtRut.getText());
               auxCliente.setNombre(this.txtNombre.getText());
        
               Negocio auxNegocio = new Negocio();
               if (auxNegocio.buscaCliente(this.txtRut.getText()).getRut().isEmpty())
               {
                  auxNegocio.ingresaCliente(auxCliente);
                  JOptionPane.showMessageDialog(null, "Datos guardados" );
               } //Fin if cliente existe
               else
               {
                  JOptionPane.showMessageDialog(null, "Cliente ya existe" );
               } //Fin else cliente existe
            } //Fin else datos en blanco
        } //Fin try
        catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null, "Datos No guardados" + ex.getMessage());
        } //Fin catch
        this.limpiarCampos();
        this.mostrar();
    }//GEN-LAST:event_btoGuardarActionPerformed

    private void btoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoEliminarActionPerformed
        // TODO add your handling code here:
        try
        {
           if (this.txtRut.getText().isEmpty())
           {
               JOptionPane.showMessageDialog(null, "Ingresa Datos Gil" );
           } //Fin datos en blanco
           else
           {
              if (JOptionPane.showConfirmDialog(null, "Esta seguro de Eliminar ?") == JOptionPane.OK_OPTION) 
              {                
                 Negocio auxNegocio = new Negocio();
                 if (auxNegocio.buscaCliente(this.txtRut.getText()).getRut().isEmpty())
                 {
                     JOptionPane.showMessageDialog(null, "Cliente no existe" );
                     
                 }
                 else
                 {
                    auxNegocio.eliminaCliente(this.txtRut.getText());
                    JOptionPane.showMessageDialog(null, "Datos Eliminados" );
                    
                 } //Fin else rut no existe
              } //Fin if desea eliminar
           } //Fin else datos en blanco
        } //Fin Try
        catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null, "Datos No guardados" + ex.getMessage());
        
        }
        this.limpiarCampos();
        this.mostrar();
        
        
    }//GEN-LAST:event_btoEliminarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.mostrar();
    }//GEN-LAST:event_formWindowOpened

    private void btoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSiguienteActionPerformed
        // TODO add your handling code here:
        if ((this.getFila() + 1) > this.getUltimo())
           this.setFila(this.getUltimo());
        else
           this.setFila(this.getFila() + 1);
        this.mostrar();
        
        
    }//GEN-LAST:event_btoSiguienteActionPerformed

    private void btoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoAnteriorActionPerformed
        // TODO add your handling code here:
        if ((this.getFila() - 1) < 1)
            this.setFila(1);
        else
            this.setFila(this.getFila() - 1);
        this.mostrar();

    }//GEN-LAST:event_btoAnteriorActionPerformed

    private void btoPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoPrimeroActionPerformed
        // TODO add your handling code here:
        this.setFila(1);
        this.mostrar();
    }//GEN-LAST:event_btoPrimeroActionPerformed

    private void btoUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoUltimoActionPerformed
        // TODO add your handling code here:       
        this.setFila(this.getUltimo());
        this.mostrar();
        
    }//GEN-LAST:event_btoUltimoActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoActuralizar;
    private javax.swing.JButton btoAnterior;
    private javax.swing.JButton btoConsultar;
    private javax.swing.JButton btoEliminar;
    private javax.swing.JButton btoGuardar;
    private javax.swing.JButton btoPrimero;
    private javax.swing.JButton btoSalir;
    private javax.swing.JButton btoSiguiente;
    private javax.swing.JButton btoUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPosicion;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fila
     */
    public int getFila() {
        return fila;
    }

    /**
     * @param fila the fila to set
     */
    public void setFila(int fila) {
        this.fila = fila;
    }

    /**
     * @return the ultimo
     */
    public int getUltimo() {
        return ultimo;
    }

    /**
     * @param ultimo the ultimo to set
     */
    public void setUltimo(int ultimo) {
        this.ultimo = ultimo;
    }
}
